version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn hospitalmanagement.wsgi:application --bind 0.0.0.0:8000
        --timeout 180
        --workers 2
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - fastapi

  fastapi:
    build: ./arrhythmia_api
    container_name: arrhythmia_api
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akram
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
